### PR TITLE
New configuration parameter exempt_pod

### PR DESCRIPTION
**Pull request by jonasbn**
Hello,

I have implemented a configurable parameter exempt_pod for allowing the user of the policy to specify that POD should not be evaluated. This is a first shot, I would love to be able to do this on two levels so I could differentiate keywords matching actual part of POD and casual comments in POD, but this would require a POD parser. This first implementation can be regarded as a starting point for further exploration of the problem area.

Looking forward to hearing from you,

jonasbn

### CODE REVIEW

**Comment by petdance** [comment]
@jonasbn Is this still something worth pursuing?

**Comment by jonasbn** [comment]
Hi @petdance,

I would love for this to be implemented and for the _dots to go away_ (please see attached screenshot).

todos in pod

You deliver useful and configurable software of high standards, so my PR is an attempt to honor this, but it is your call. I can disable the policy locally where appropriate using:

```perl
1;

## no critic (ProhibitFlagComments)

__END__

=pod
````

But that would require that I do it  in a lot of places instead of implementing it on a policy level. 

It is your call :-)

**Comment by petdance** [comment]
So if I'm understanding, you want to make it so that this passes:

```
=head1 TODO
```

But that this code

```
# TODO Still have to add the third argument
```

would not pass.  Is that correct?  (Although I'm not clear what I'm supposed to be seeing in the screenshot.)

If so, that sounds reasonable.  Can you please put all this together into a new PR against `dev`?

**Comment by jonasbn** [comment]
Hi @petdance,

I will create a new PR against DEV. The screenshot was to indicate a violation in the POD. 

And you are spot on in your comment.

- POD should parse (be exempt from your policy by configuration)
- Comments should not (as for your policy)

jonasbn

**Comment by petdance** [comment]
What about POD text vs. POD directives?

```
# XXX One

=head1 XXX Two

XXX Three

=cut
```

Of those, which will be exempt and which will be flagged?

**Comment by jonasbn** [comment]
Hi @petdance,

Let me clarify my view.

IMHO Perl::Critic is _primarily_ aimed at source code. Your policy is aimed at specific labels in comments in source code, where specific patterns can trigger violations based on configuration (you already know this).

Personally I have a clear distinction between source code and inline documentation (Perl and POD) since it is two different languages whereas comments are source code disabled from interpretation/compilation, however also used to annotate code constructs.

My original PR was focused on the ability to configure the policy to avoid violations for the same labels in inline documentation (POD). Since the policy implementation currently flag the configured patterns as violations, I regard this as _false-positives_, since the heading TODO is quite common in CPAN distribution documentation, at least for my distributions and POD is not comments and inline documentation is not source code.

So to avoid having POD being part of the evaluation of my source code violation, I need the proposed `except_pod` configuration parameter.

So if the patterns should be handled in inline documentation I would prefer it to be under the same premise as for source code, meaning that is should be in the state of meta-data / annotations / comments, not in the actual online documentation.

From [the POD documentation](http://perldoc.perl.org/perlpod.html):

> A format name of "comment" is common for just making notes (presumably to yourself) that won't appear in any formatted version of the Pod document:

```
=for comment
Make sure that all the available options are documented!
```

So that particular formatting will not rendered as part of the POD, everything else is regarded as part of the documentation.

Evaluating your example, with `exempt_pod` enabled (this is a mind experiment not an actual evaluation)

```
# XXX One <- violation 

=head1 XXX Two <- not violation

XXX Three <- not violation

=cut
```

And if the policy should both be used to evaluate source code and inline documentation, based on the POD documentation mentioned, it should look as follows:

```
# XXX One <- violation 

=head1 XXX Two <- not violation

XXX Three <- not violation

=for comment
TODO: fix speling errors in the documentation <- violation

=cut
```

This is beyond my current PR, which aims to enables the capability to distinguish between source code and inline documentation. 

I am not sure how Perl comments are handled, when mixed in with POD, but I would expect these to be rendered, but as source code comments. This will require some additional testing.

Please let me know what the premises are for the policy and I will evaluate whether my PR is still relevant, since I have interpreted the premise based on my own use-case and personal perspective on source code and inline documentation.

**Comment by petdance** [comment]
I'm almost wondering if the default should be that it doesn't look in POD, and that your `exempt_pod` is unnecessary.

**Comment by petdance** [comment]
I'm wondering if the default should be that it doesn't look in POD, and that it only looks in inline comments, and that your `exempt_pod` is unnecessary.

**Comment by jonasbn** [comment]
Hi @petdance 

That would work too and then it could be considered to extend the policy to evaluate POD under the proper circumstances. 

Only argument against this is that it might be regarded as a change in behaviour.

jonasbn

**Comment by petdance** [comment]
> I will create a new PR against DEV.

I'm still waffling on this.  I'm leaning towards using your patch.  Can you please do that new PR?

**Comment by jonasbn** [comment]
I am closing this PR, since another PR (#20) was created as requested

**Pull request closed without merging**
